[package]
name = "uquery"
version = "0.4.2"
edition = "2024"

[dependencies]
axum = { version = "0.8" }
tokio = {version="1.41",features = ["full"] }
tokio-util = { version = "*",features = ["io","io-util"] }
serde = { version = "1.0", features = ["derive"] }
duckdb = { version = "1.2.2", features = ["extensions-full"] }
arrow = {version = "54", features = ["arrow-json","arrow-csv","arrow-ipc","chrono-tz"]}
serde_json = "1.0"
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
tower = "*"
tower-http = { version = "*", features = ["compression-gzip","cors"]}
clap = { version = "4.5", features = ["derive","env"] }

[dev-dependencies]
polars = { version = "0.46"}
polars-io = { version = "0.46",features = ["ipc_streaming","json"]}