name: uQuery CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust
        run: rustup update && rustup component add rustfmt clippy

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose