name: uQuery CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          key: clippy

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2
        with:
          key: test

      - name: Run tests
        run: cargo test --verbose